### ISSUE TITLE
Simultaneous session initialization with PreKeyWhisperMessage

### ISSUE THREAD

**Issue by schnef** [WhisperSystems/libaxolotl-java#12]
Assume two parties want to start a session simultaneously by sending a PreKeyWhisperMessage. Both initialize their end of the session and send a PreKeyWhisperMessage. Both sides will now try to complete the session by looking up the prekey with the previously issued base key. The result is that there are two sessions in place! As far as I understand the code, there is nothing in place to prevent this to happen or do I miss something? 
This would mean both sessions are one-way only and the chain keys in the ratchet will not be updated, which is a problematic. 
I am new to all this Axolotl stuff, so this may be the wrong place to ask this question.

**Comment by strb** [comment]
If you take a look at the SessionStore interface, you will notice that this library doesn't really allow for there to be two different sessions associated with the same counterpart. If you have a session with someone else, and you receive a PreKeyWhisperMessage from them, your SessionCipher object will complete this new session using the SessionBuilder, which will replace the old SessionRecord with the newly created one, overwriting your old session.

**Comment by schnef** [comment]
Ok, so both parties drop their initial session state and build the new session state using the other side's base key. Now, what happens next?

**Comment by moxie0** [comment]
We prefer to use GitHub as an issue tracker rather than a discussion forum.  If you have an opinion you'd like to share, the mailing list is the best place for that.  For questions, the support center or support@whispersystems.org.  Thanks!
