### ISSUE TITLE
Reduce code duplication in ECPublicKey and ECPrivateKey

### ISSUE THREAD

**Issue by janriemer** [WhisperSystems/libaxolotl-java#8]
Not related to the issue
------------------------------
Dear WhisperSystems team,
first of all thank you for the great work you are doing.
I think the products you offer will have a positive impact on the way we think about our privacy
and I hope that other products get inspired by your work.
**************************************
Now to the actual issue
-------------------------------
*Notice: I am just getting started with open source projects and WhisperSystems' software
so please bare with me if I don't see the whole impact of my change proposal.* :wink:

The interfaces [ECPublicKey] (https://github.com/WhisperSystems/libaxolotl-java/blob/ef36fe43d5efcf75950779d0971e9e0e02730172/java/src/main/java/org/whispersystems/libaxolotl/ecc/ECPublicKey.java) and [ECPrivateKey] (https://github.com/WhisperSystems/libaxolotl-java/blob/ef36fe43d5efcf75950779d0971e9e0e02730172/java/src/main/java/org/whispersystems/libaxolotl/ecc/ECPrivateKey.java) share the same method signatures.
My proposed change is, in order to reduce code duplication, to aggregate these method signatures
into a super interface. I propose the name *SerializableKey* for the new interface.
```java
public interface SerializableKey {
  // shared method signatures here
}

public interface ECPublicKey extends SerializableKey {
  // we only need to add the final field
}

public interface ECPrivateKey extends SerializableKey {
  // nothing to add here
}
```
#### :heavy_minus_sign: The argument **against** this change
-    Due to the strict separation of ECPublicKey and ECPrivateKey (no common interface),
     we avoid having potencial security flaws -> e.g. injecting an instance of ECPrivateKey, although it
     is meant to be an instance of ECPublicKey

#### :heavy_plus_sign: The arguments in favour of this change
-    reduce code duplication
-    easier for new developers to recognize the similarities between ECPublicKey and ECPrivateKey
-    more generalization and therefore the generalized interface can be used elsewhere as well
     (see below)

One example for using this new interface in other parts is in the class [PublicKey] (https://github.com/WhisperSystems/TextSecure/blob/e130d0a3e62d833e799f32a463de01e42f28b5ca/src/org/thoughtcrime/securesms/crypto/PublicKey.java) of the [TextSecure for Android Repository] (https://github.com/WhisperSystems/TextSecure): this class could implement the new SerializableKey interface, because some methods share the same signatures.
I haven't dug deep enough into the code yet to spot other places where it could be used, but
the good thing is that it can be introduced incrementally, because the current code won't break without the use of the SerializableKey interface

I appreciate any thoughts on this. :kissing_heart: 
If this could be integrated, I would love to send you a PR.
Thank you and best regards,
Jan

**Comment by moxie0** [comment]
These interfaces are strictly for type safety.  We could just pass around byte[] if we wanted a minimal interface, but we explicitly want this.
